import { copyFileSync, mkdirSync } from "node:fs";
import { builtinModules } from "node:module";
import process from "node:process";
import esbuild from "esbuild";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";
const outdir = prod ? "build" : ".";

// Copy plugin assets to build/ and optionally to test vault
const copyAssets = {
	name: "copy-assets",
	setup(build) {
		build.onEnd(() => {
			if (prod) {
				mkdirSync("build", { recursive: true });
				copyFileSync("manifest.json", "build/manifest.json");
				copyFileSync("styles.css", "build/styles.css");

				// Uncomment and adjust to copy build output to your test vault:
				// const VAULT_PLUGIN_DIR = "test/MyVault/.obsidian/plugins/obsidian-archivist";
				// if (existsSync(VAULT_PLUGIN_DIR)) {
				// 	copyFileSync(`${outdir}/main.js`, `${VAULT_PLUGIN_DIR}/main.js`);
				// 	copyFileSync("manifest.json", `${VAULT_PLUGIN_DIR}/manifest.json`);
				// 	copyFileSync("styles.css", `${VAULT_PLUGIN_DIR}/styles.css`);
				// }
			}
		});
	},
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules,
		...builtinModules.map((m) => `node:${m}`),
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: `${outdir}/main.js`,
	minify: prod,
	plugins: [copyAssets],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
