// MismatchRecoveryModal — recovery dialog when the local vault_id no longer
// matches the vault_id recorded on Dropbox. Triggered when the FSM reports
// BLOCKED with reason VAULT_ID_MISMATCH (or VAULT_META_CORRUPT — the modal
// covers both shapes; see opts.kind).
//
// The common cause is a plugin reset (data.json wiped, fresh vault_id auto-
// generated) against an existing Dropbox folder that still carries the
// previous installation's vault_meta.json. The remote chain is intact and
// owned by the same user — so adopting the remote vault_id is the safe
// recovery for almost every case.
//
// Why a dedicated modal rather than reusing AdoptVaultModal: AdoptVaultModal
// only triggers when the local side has NO vault_id (consistency 'adopt-
// remote' kind). That flow is unreachable when the local id was already
// auto-generated on plugin onload, which is the path users hit when their
// data.json gets reset. This modal is the missing recovery surface for the
// 'mismatch' / 'remote-corrupt' kinds.

import { Modal, type App } from 'obsidian';
import type { ModalHandle } from './ConfirmRestoreModal';
import { S } from './strings';

// ---------------------------------------------------------------------------
// Public types
// ---------------------------------------------------------------------------

export type MismatchKind = 'mismatch' | 'remote-corrupt';

export interface MismatchRecoveryRecord {
  kind: MismatchKind;
  /** Local vault_id auto-generated by the current install. Null when
   *  data.json has no vault_id (shouldn't happen for this modal but safe). */
  localVaultId: string | null;
  /** Remote vault_id from <prefix>/vault_meta.json — null when the meta is
   *  corrupt (kind === 'remote-corrupt'). */
  remoteVaultId: string | null;
  /** Remote vault_name as recorded in vault_meta. Null when corrupt. */
  remoteVaultName: string | null;
  /** Raw error message when remote is corrupt — surfaced as diagnostic detail. */
  rawError: string | null;
}

export interface MismatchRecoveryModalOpts {
  record: MismatchRecoveryRecord;
  /** Called when the user clicks "Adopt remote ID". Resolves on success. */
  onAdoptRemote: () => Promise<void>;
  /** Optional escape-hatch for users who know their remote is the wrong
   *  vault and want to start a fresh backup chain. Closes the modal; the
   *  caller is expected to surface settings (vault_prefix change). */
  onChangePrefix?: () => void;
  /** Called when the user dismisses without acting. Banner stays. */
  onCancel: () => void;
}

// ---------------------------------------------------------------------------
// Pure rendering — exercised directly by tests
// ---------------------------------------------------------------------------

export function renderMismatchRecoveryContent(
  handle: ModalHandle,
  opts: MismatchRecoveryModalOpts,
): void {
  const { record, onAdoptRemote, onChangePrefix, onCancel } = opts;

  handle.setTitle(
    record.kind === 'remote-corrupt'
      ? S.MISMATCH_RECOVERY_TITLE_CORRUPT
      : S.MISMATCH_RECOVERY_TITLE_MISMATCH,
  );

  if (record.kind === 'remote-corrupt') {
    handle.setBody(S.MISMATCH_RECOVERY_BODY_CORRUPT);
    if (record.rawError) {
      handle.addLine(`${S.MISMATCH_RECOVERY_LABEL_RAW}: ${record.rawError}`);
    }
    handle.addLine(S.MISMATCH_RECOVERY_HINT_CORRUPT);
    handle.addButton(S.MISMATCH_RECOVERY_CANCEL, true, () => {
      onCancel();
      handle.close();
    });
    handle.onKeydown((key) => {
      if (key === 'Escape') {
        onCancel();
        handle.close();
      }
    });
    return;
  }

  // kind === 'mismatch'
  handle.setBody(S.MISMATCH_RECOVERY_BODY_MISMATCH);
  if (record.localVaultId) {
    handle.addLine(`${S.MISMATCH_RECOVERY_LABEL_LOCAL}: ${record.localVaultId}`);
  }
  if (record.remoteVaultId) {
    const name = record.remoteVaultName ? ` (${record.remoteVaultName})` : '';
    handle.addLine(`${S.MISMATCH_RECOVERY_LABEL_REMOTE}: ${record.remoteVaultId}${name}`);
  }
  handle.addLine(S.MISMATCH_RECOVERY_HINT_MISMATCH);

  handle.addButton(S.MISMATCH_RECOVERY_ADOPT, false, () => {
    void (async (): Promise<void> => {
      try {
        await onAdoptRemote();
      } catch {
        // Swallow — error reporting is the caller's job (toast or
        // banner). Re-throwing would surface as an unhandled rejection
        // from this fire-and-forget click handler.
      } finally {
        // Always close — leaving the modal open after a failed adopt
        // would confuse users who expect immediate UI feedback.
        handle.close();
      }
    })();
  });
  if (onChangePrefix) {
    handle.addButton(S.MISMATCH_RECOVERY_CHANGE_PREFIX, false, () => {
      onChangePrefix();
      handle.close();
    });
  }
  // Cancel is the safe default — reflexive Enter shouldn't perform an
  // adoption that overwrites the local vault_id.
  handle.addButton(S.MISMATCH_RECOVERY_CANCEL, true, () => {
    onCancel();
    handle.close();
  });

  handle.onKeydown((key) => {
    if (key === 'Escape') {
      onCancel();
      handle.close();
    }
  });
}

// ---------------------------------------------------------------------------
// MismatchRecoveryModal — Obsidian Modal subclass
// ---------------------------------------------------------------------------

export class MismatchRecoveryModal extends Modal {
  private triggerEl: HTMLElement | null = null;

  constructor(
    app: App,
    private readonly opts: MismatchRecoveryModalOpts,
  ) {
    super(app);
  }

  onOpen(): void {
    const el = activeDocument.activeElement;
    this.triggerEl = el instanceof HTMLElement ? el : null;
    const handle = this.makeHandle();
    renderMismatchRecoveryContent(handle, this.opts);
  }

  onClose(): void {
    this.contentEl.empty();
  }

  private makeHandle(): ModalHandle {
    let titleEl: HTMLElement | null = null;
    let bodyEl: HTMLElement | null = null;
    const controller = new AbortController();
    const closeFn = (): void => {
      this.triggerEl?.focus();
      this.close();
    };
    return {
      setTitle: (title) => {
        if (!titleEl) titleEl = this.contentEl.createEl('h2');
        titleEl.textContent = title;
      },
      setBody: (body) => {
        if (!bodyEl) bodyEl = this.contentEl.createEl('p');
        bodyEl.textContent = body;
      },
      addLine: (line) => {
        this.contentEl.createEl('p', { text: line });
      },
      addButton: (label, isDefault, onClick) => {
        const btn = this.contentEl.createEl('button', { text: label });
        if (isDefault) btn.setAttribute('autofocus', '');
        btn.addEventListener('click', onClick);
      },
      close: () => {
        controller.abort();
        closeFn();
      },
      onKeydown: (handler) => {
        this.modalEl.addEventListener(
          'keydown',
          (e: KeyboardEvent) => handler(e.key),
          { signal: controller.signal },
        );
      },
    };
  }
}
